// ──────────────────────────────────────────────
// Room ID generation
// ──────────────────────────────────────────────

/**
 * ARCH_REVIEW: Room ID encoding scheme.
 *
 * We take a 128-bit UUID (randomUUID), interpret it as bytes, base-62 encode
 * (0-9a-zA-Z), and truncate to 7 chars prefixed with "dg-".
 *
 * Entropy: 7 base-62 chars = log2(62^7) ≈ 41.6 bits.
 * Collision probability with 10,000 concurrent rooms:
 *   P ≈ n² / (2 * 2^41.6) ≈ 1e8 / 3.2e12 ≈ 0.003% — acceptable for ephemeral rooms.
 * If scaling significantly, increase to 10+ chars or use nanoid.
 */

const BASE62 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
const ROOM_ID_LENGTH = 7;
const ROOM_ID_PREFIX = 'dg-';

export function generateRoomId(): string {
  // crypto.randomUUID() returns a UUID v4 string like "f47ac10b-58cc-4372-a567-0e02b2c3d479"
  const uuid = crypto.randomUUID();
  // Remove dashes, parse as hex, convert to a bigint, then encode in base62
  const hex = uuid.replace(/-/g, '');
  // We only need ~42 bits of entropy; use the first 10 hex chars = 40 bits
  const truncatedHex = hex.substring(0, 10);
  const bigint = BigInt('0x' + truncatedHex);
  return ROOM_ID_PREFIX + toBase62(bigint).padStart(ROOM_ID_LENGTH, '0');
}

export function isValidRoomId(id: string): boolean {
  const pattern = new RegExp(`^${ROOM_ID_PREFIX}[${BASE62}]{${ROOM_ID_LENGTH}}$`);
  return pattern.test(id);
}

function toBase62(num: bigint): string {
  if (num === 0n) return '0';
  let result = '';
  const base = 62n;
  while (num > 0n) {
    result = BASE62[Number(num % base)] + result;
    num = num / base;
  }
  return result;
}

// ──────────────────────────────────────────────
// Ephemeral nickname generation
// ──────────────────────────────────────────────

/**
 * ARCH_REVIEW: Simple combinatorial nickname generator.
 *
 * 200 adjectives × 200 nouns = 40,000 unique combinations.
 * If we see nickname collisions in dogfooding, expand both word lists to 500+ each
 * (250,000 combos) or add a 2-digit suffix.
 */

const adjectives = [
  'Amber', 'Azure', 'Bold', 'Bright', 'Calm', 'Cool', 'Crimson', 'Crystal',
  'Daring', 'Dark', 'Deep', 'Dewy', 'Dim', 'Dusty', 'Eager', 'Electric',
  'Faint', 'Fierce', 'Fiery', 'Fluffy', 'Frosty', 'Gentle', 'Glad', 'Glossy',
  'Golden', 'Grand', 'Gray', 'Green', 'Happy', 'Harsh', 'Hazy', 'Heavy',
  'Hidden', 'Holy', 'Humble', 'Icy', 'Jade', 'Jolly', 'Jovial', 'Joyous',
  'Keen', 'Kind', 'Large', 'Lazy', 'Lemon', 'Light', 'Lively', 'Lone',
  'Long', 'Loud', 'Lucky', 'Lunar', 'Lush', 'Mellow', 'Mild', 'Minty',
  'Misty', 'Mixed', 'Muted', 'Neon', 'Noble', 'Ocean', 'Olive', 'Onyx',
  'Pale', 'Petal', 'Plain', 'Plum', 'Polite', 'Proud', 'Pure', 'Quick',
  'Quiet', 'Rapid', 'Rare', 'Raw', 'Red', 'Rich', 'Rough', 'Royal',
  'Ruby', 'Rustic', 'Salty', 'Sandy', 'Sharp', 'Shy', 'Silent', 'Silky',
  'Silver', 'Simple', 'Slate', 'Sleek', 'Slick', 'Slow', 'Small', 'Smart',
  'Smooth', 'Snug', 'Solar', 'Solid', 'Sour', 'Spark', 'Steady', 'Steel',
  'Stiff', 'Still', 'Stone', 'Storm', 'Stout', 'Strange', 'Strict', 'Sturdy',
  'Subtle', 'Sunny', 'Super', 'Sweet', 'Swift', 'Tame', 'Tender', 'Tense',
  'Thin', 'Tidy', 'Tight', 'Tiny', 'Tough', 'Tranquil', 'True', 'Turbo',
  'Ultra', 'Vague', 'Vast', 'Velvet', 'Vivid', 'Warm', 'Wavy', 'Waxy',
  'Weak', 'Wild', 'Wise', 'Witty', 'Wooly', 'Worthy', 'Young', 'Zany',
  'Zealous', 'Zen', 'Bitter', 'Bland', 'Blunt', 'Breezy', 'Brief', 'Bronze',
  'Bulky', 'Bumpy', 'Cherry', 'Chilly', 'Clean', 'Cloudy', 'Clumsy', 'Coarse',
  'Cozy', 'Crisp', 'Curly', 'Damp', 'Dandy', 'Dense', 'Dinky', 'Dizzy',
  'Dreary', 'Drowsy', 'Drunk', 'Dry', 'Dull', 'Elastic', 'Elite', 'Empty',
  'Equal', 'Exact', 'Fancy', 'Fatal', 'Fat', 'Firm', 'Fixed', 'Flaky',
  'Flat', 'Fleet', 'Flex', 'Flint', 'Flush', 'Fond', 'Frail', 'Frank',
  'Fresh', 'Frizzy', 'Fuzzy', 'Gaunt', 'Giddy', 'Gleaming', 'Gloomy', 'Grainy',
  'Greasy', 'Grim', 'Gritty', 'Grouchy', 'Gruff', 'Gummy', 'Hairy', 'Handy',
  'Hard', 'Harsh', 'Hasty', 'Haunting', 'Hazy', 'Hearty', 'Heavy', 'Hollow',
  'Hot', 'Huge', 'Husk', 'Idle', 'Irate', 'Jagged', 'Jazzy', 'Jittery',
  'Juicy', 'Keen', 'Knobby', 'Lacy', 'Lanky', 'Leafy', 'Leaky', 'Lean',
  'Lethal', 'Level', 'Limp', 'Liquid', 'Lithe', 'Little', 'Loose', 'Low',
  'Loyal', 'Lucid', 'Lumpy', 'Lurid', 'Macho', 'Mad', 'Magnetic', 'Majestic',
  'Massive', 'Mature', 'Mean', 'Merry', 'Metal', 'Milky', 'Mini', 'Minor',
  'Misty', 'Mixed', 'Modest', 'Moist', 'Moody', 'Muddy', 'Muggy', 'Murky',
  'Mushy', 'Musty', 'Mute', 'Narrow', 'Nasty', 'Naughty', 'Nervy', 'Nifty',
  'Nimble', 'Nippy', 'Noble', 'Noisy', 'Normal', 'Novel', 'Numb', 'Obese',
  'Odd', 'Oily', 'Opaque', 'Open', 'Orange', 'Orderly', 'Organic', 'Ornate',
  'Pale', 'Passive', 'Pastel', 'Patient', 'Placid', 'Playful', 'Pleasant', 'Plump',
  'Pointed', 'Polished', 'Poor', 'Porous', 'Posh', 'Powdery', 'Prickly', 'Prim',
  'Prime', 'Primal', 'Proper', 'Public', 'Puffy', 'Puny', 'Purple', 'Pushy',
  'Quaint', 'Quartz', 'Queasy', 'Quirky', 'Radiant', 'Rainy', 'Random', 'Rank',
  'Rare', 'Raspy', 'Rational', 'Rattan', 'Raw', 'Real', 'Red', 'Regal',
  'Remote', 'Rich', 'Rigid', 'Ripe', 'Risky', 'Roasted', 'Robust', 'Rocket',
  'Rough', 'Round', 'Rowdy', 'Rubber', 'Ruddy', 'Rusty', 'Sacred', 'Safe',
  'Salty', 'Sandy', 'Sappy', 'Sassy', 'Satin', 'Scarce', 'Scary', 'Scented',
  'Scorn', 'Secret', 'Secure', 'Sedate', 'Select', 'Senior', 'Severe', 'Shady',
  'Shallow', 'Sharp', 'Sheer', 'Shiny', 'Short', 'Shrill', 'Shy', 'Silly',
  'Simple', 'Sincere', 'Sinewy', 'Sizzling', 'Skilled', 'Sleek', 'Slick', 'Slim',
  'Sloppy', 'Slow', 'Sly', 'Small', 'Smart', 'Smoky', 'Smooth', 'Smug',
  'Snappy', 'Snazzy', 'Sneaky', 'Snug', 'Soaring', 'Sober', 'Soft', 'Solar',
  'Solid', 'Somber', 'Sonic', 'Sooty', 'Sore', 'Sour', 'Sparky', 'Sparse',
  'Speedy', 'Spicy', 'Spiky', 'Spiral', 'Splendid', 'Spotty', 'Spry', 'Square',
  'Stable', 'Stale', 'Standard', 'Stark', 'Steady', 'Steep', 'Stellar', 'Sticky',
  'Stiff', 'Still', 'Stingy', 'Stoic', 'Stony', 'Stormy', 'Stout', 'Strange',
  'Strict', 'Strike', 'Stringy', 'Strong', 'Stubborn', 'Stuffy', 'Sturdy', 'Subtle',
  'Sudden', 'Sulky', 'Sullen', 'Summary', 'Sunny', 'Super', 'Supreme', 'Sure',
  'Surreal', 'Svelte', 'Swanky', 'Sweet', 'Swift', 'Tacky', 'Tame', 'Tan',
  'Tangy', 'Tart', 'Taut', 'Tender', 'Tense', 'Tepid', 'Testy', 'Thick',
  'Thin', 'Thirsty', 'Thorny', 'Tidy', 'Tight', 'Timid', 'Tiny', 'Tired',
  'Tolerable', 'Torn', 'Total', 'Tough', 'Toxic', 'Tranquil', 'Triple', 'Trite',
  'Tropical', 'True', 'Tubby', 'Turbid', 'Turbo', 'Twin', 'Ultra', 'Uneven',
  'Unique', 'United', 'Unreal', 'Urban', 'Urgent', 'Utter', 'Vacant', 'Vague',
  'Vain', 'Valid', 'Vast', 'Velvet', 'Vengeful', 'Venom', 'Verdant', 'Versed',
  'Vexed', 'Vibrant', 'Victory', 'Violet', 'Virile', 'Virtual', 'Viscous', 'Vital',
  'Vivid', 'Vocal', 'Void', 'Wacky', 'Warm', 'Wary', 'Washed', 'Wasteful',
  'Wavy', 'Waxy', 'Weak', 'Wealthy', 'Weary', 'Webbed', 'Wee', 'Weekly',
  'Weighty', 'Weird', 'Whimsy', 'Whiny', 'Whisper', 'White', 'Whole', 'Wicked',
  'Wide', 'Wild', 'Willing', 'Wily', 'Windy', 'Wiry', 'Wise', 'Wispy',
  'Witty', 'Wobbly', 'Woozy', 'Worn', 'Worried', 'Worthy', 'Wrathful', 'Wry',
  'Yellow', 'Yielding', 'Young', 'Youthful', 'Zany', 'Zealous', 'Zen', 'Zesty',
  'Zippy', 'Zonal', 'Able', 'Acid', 'Acute', 'Aged', 'Agile', 'Alive',
  'Alone', 'Aloof', 'Ancient', 'Angry', 'Antique', 'Apple', 'Aqua', 'Arctic',
  'Ardent', 'Arid', 'Ashen', 'Ashy', 'Atomic', 'Aware', 'Awestruck', 'Baked',
  'Bald', 'Bare', 'Bashful', 'Bawdy', 'Beige', 'Bent', 'Bewildered', 'Big',
  'Binary', 'Bitter', 'Bizarre', 'Blank', 'Bleak', 'Blind', 'Blissful', 'Blond',
  'Blotchy', 'Blue', 'Bold', 'Bony', 'Bossy', 'Bouncy', 'Bowed', 'Brawny',
  'Brave', 'Brief', 'Bright', 'Brisk', 'Broad', 'Broken', 'Bronze', 'Brown',
  'Bubbly', 'Budding', 'Buff', 'Buggy', 'Bumpy', 'Burning', 'Busy', 'Caged',
  'Canny', 'Caring', 'Casual', 'Caustic', 'Cautious', 'Cave', 'Chalky', 'Champ',
  'Charming', 'Cheap', 'Cheeky', 'Cheerful', 'Cheesy', 'Chic', 'Chief', 'Chill',
  'Chilled', 'Chilly', 'Chubby', 'Chunky', 'Civil', 'Classic', 'Classy', 'Clay',
  'Clean', 'Clear', 'Clever', 'Cloudy', 'Clumsy', 'Coarse', 'Coastal', 'Colossal',
  'Comfy', 'Common', 'Complex', 'Concrete', 'Cool', 'Copper', 'Coral', 'Correct',
  'Cosmic', 'Costly', 'Cotton', 'Courage', 'Cozy', 'Crafty', 'Cranky', 'Crazy',
  'Creamy', 'Creepy', 'Crisp', 'Crude', 'Cruel', 'Cuddly', 'Cult', 'Cunning',
  'Curly', 'Current', 'Curvy', 'Cushy', 'Cute', 'Cyclic', 'Daily', 'Dainty',
  'Damp', 'Dandy', 'Dapper', 'Dark', 'Daring', 'Dated', 'Dead', 'Deadly',
  'Deafening', 'Dear', 'Debonair', 'Decent', 'Deep', 'Deft', 'Delicate', 'Dense',
  'Desert', 'Desired', 'Devout', 'Dewy', 'Diamond', 'Digital', 'Diligent', 'Dim',
  'Dimpled', 'Dinky', 'Dire', 'Dirty', 'Discrete', 'Dismal', 'Distant', 'Dizzy',
  'Docile', 'Dotted', 'Double', 'Doubtful', 'Drab', 'Drafty', 'Dramatic', 'Dreary',
  'Drenched', 'Drowsy', 'Dual', 'Dumb', 'Durable', 'Dusky', 'Dusty', 'Dwarf',
  'Dynamic', 'Eager', 'Early', 'Earthy', 'Easy', 'Eerie', 'Elastic', 'Elegant',
  'Elite', 'Elm', 'Elusive', 'Embryo', 'Emerald', 'Empty', 'Endless', 'Epic',
  'Equal', 'Eternal', 'Ethnic', 'Even', 'Event', 'Evil', 'Exact', 'Excess',
  'Expert', 'Extra', 'Extreme', 'Fabled', 'Fabulous', 'Faded', 'Faint', 'Fair',
  'Fake', 'Fallen', 'Famed', 'Fancy', 'Fancy', 'Fatal', 'Fateful', 'Fatherly',
  'Faulty', 'Favored', 'Feared', 'Fearless', 'Feather', 'Feisty', 'Feline', 'Feral',
  'Fertile', 'Festive', 'Fetal', 'Feudal', 'Fevered', 'Fiber', 'Fickle', 'Fierce',
  'Fiery', 'Fifth', 'Filmy', 'Filthy', 'Final', 'Fine', 'Finer', 'Firm',
  'First', 'Fiscal', 'Fizzy', 'Flabby', 'Flaky', 'Flashy', 'Flat', 'Flawed',
  'Fleet', 'Flexed', 'Flicker', 'Flinty', 'Flippant', 'Float', 'Floating', 'Flooded',
  'Floral', 'Flowing', 'Fluid', 'Flushed', 'Flute', 'Flyaway', 'Foamy', 'Focal',
  'Foggy', 'Folded', 'Fond', 'Foolish', 'Forced', 'Foreign', 'Forest', 'Forked',
  'Formal', 'Former', 'Foul', 'Fourth', 'Frail', 'Frank', 'Frantic', 'Frayed',
  'Free', 'Frequent', 'Fresh', 'Fretted', 'Friendly', 'Frigid', 'Frizzy', 'Frosty',
  'Frothy', 'Frozen', 'Frugal', 'Fruit', 'Fruitful', 'Frumpy', 'Fugitive', 'Full',
  'Fuming', 'Furry', 'Furtive', 'Fused', 'Fussy', 'Fuzzy', 'Gainful', 'Gamy',
  'Gaping', 'Garbled', 'Gaseous', 'Gauzy', 'Gawky', 'General', 'Generous', 'Genetic',
  'Genial', 'Gentle', 'Genuine', 'Germane', 'Ghastly', 'Ghostly', 'Giant', 'Giddy',
  'Gifted', 'Gilded', 'Girly', 'Given', 'Glacial', 'Glad', 'Glam', 'Glaring',
  'Glass', 'Gleaming', 'Gleeful', 'Glib', 'Glimmer', 'Glistening', 'Global', 'Gloomy',
  'Glorious', 'Glossy', 'Glowing', 'Glum', 'Gluten', 'Gnarled', 'Gnarly', 'Gnome',
  'Goaded', 'Going', 'Golden', 'Good', 'Gooey', 'Goofy', 'Gorgeous', 'Gothic',
  'Graceful', 'Gradual', 'Grained', 'Grand', 'Granite', 'Grassy', 'Grateful', 'Grave',
  'Gravel', 'Great', 'Greedy', 'Green', 'Gregarious', 'Grey', 'Grief', 'Grim',
  'Grinding', 'Gripping', 'Gritty', 'Grizzled', 'Groaning', 'Groggy', 'Groomed', 'Grooved',
  'Gross', 'Grotesque', 'Grouchy', 'Grounded', 'Growing', 'Growling', 'Growth', 'Grubby',
  'Grueling', 'Gruesome', 'Gruff', 'Grumpy', 'Guarded', 'Guileless', 'Guilt', 'Gullible',
  'Gummy', 'Gushy', 'Gusty', 'Gutsy', 'Hairy', 'Half', 'Handsome', 'Handy',
  'Hanging', 'Hapless', 'Happy', 'Hard', 'Hardy', 'Harmful', 'Harmless', 'Harmonic',
  'Harsh', 'Hasty', 'Hated', 'Haunting', 'Hazy', 'Headlong', 'Healthy', 'Heartfelt',
  'Hearty', 'Heated', 'Heavenly', 'Heavy', 'Hectic', 'Hefty', 'Helpful', 'Helpless',
  'Heroic', 'Hidden', 'High', 'Hill', 'Hilly', 'Hip', 'Hissing', 'Historic',
  'Hollow', 'Holy', 'Homeless', 'Homely', 'Honest', 'Honey', 'Honored', 'Hopeful',
  'Horizontal', 'Horny', 'Hostile', 'Hot', 'Huge', 'Humble', 'Humid', 'Hungry',
  'Hunky', 'Hunter', 'Hurried', 'Hushed', 'Husky', 'Hybrid', 'Hyper', 'Hypnotic',
  'Icy', 'Ideal', 'Idle', 'Ignited', 'Ignored', 'Icy', 'Ill', 'Illegal',
  'Illusive', 'Imaginary', 'Immense', 'Immortal', 'Immune', 'Impact', 'Imperial', 'Impish',
  'Implicit', 'Important', 'Imported', 'Imposing', 'Impure', 'Inborn', 'Inbound', 'Inbred',
  'Incisive', 'Indigo', 'Indoor', 'Induced', 'Infinite', 'Informal', 'Inherent', 'Inland',
  'Innate', 'Innocent', 'Input', 'Insane', 'Insect', 'Inside', 'Instant', 'Intact',
  'Intense', 'Intent', 'Internal', 'Intimate', 'Intrepid', 'Ionic', 'Irate', 'Iron',
  'Ironic', 'Irrational', 'Isolated', 'Ivory', 'Ivied', 'Jaded', 'Jagged', 'Jazzy',
  'Jealous', 'Jeering', 'Jelly', 'Jewel', 'Jittery', 'Jointed', 'Joking', 'Jolly',
  'Jostled', 'Jovial', 'Joyful', 'Joyous', 'Jubilant', 'Judging', 'Juiced', 'Juicy',
  'Jumbled', 'Jumbo', 'Jumpy', 'Junior', 'Jury', 'Just', 'Karmic', 'Keeled',
  'Keen', 'Key', 'Khaki', 'Killer', 'Kind', 'Kindly', 'Kinetic', 'Kingly',
  'Kinky', 'Kissable', 'Kitchen', 'Knight', 'Knobby', 'Knotted', 'Known', 'Kooky',
  'Laced', 'Lacy', 'Laden', 'Lame', 'Lanced', 'Lanky', 'Lapsed', 'Large',
  'Lasting', 'Late', 'Latent', 'Lateral', 'Latest', 'Latter', 'Laughing', 'Launched',
  'Laundry', 'Lavender', 'Leading', 'Leafy', 'Leaky', 'Leaning', 'Leaping', 'Learned',
  'Leased', 'Leather', 'Leaving', 'Lecherous', 'Legal', 'Lemon', 'Lengthy', 'Lens',
  'Leopard', 'Lesser', 'Lethal', 'Level', 'Levitating', 'Liar', 'Liberal', 'Lidded',
  'Lifeless', 'Lifted', 'Light', 'Liked', 'Lilac', 'Lily', 'Limb', 'Limp',
  'Linear', 'Linen', 'Lined', 'Liquid', 'Listed', 'Lithe', 'Litter', 'Little',
  'Live', 'Lively', 'Living', 'Lizard', 'Loaded', 'Loath', 'Lobar', 'Local',
  'Locket', 'Lofty', 'Logical', 'Lone', 'Lonely', 'Long', 'Looking', 'Loose',
  'Looted', 'Loping', 'Lopsided', 'Loquacious', 'Lordly', 'Lost', 'Loud', 'Lovable',
  'Loved', 'Lovely', 'Loving', 'Low', 'Lower', 'Loyal', 'Lucid', 'Lucky',
  'Lucent', 'Lukewarm', 'Luminous', 'Lump', 'Lumpy', 'Lunar', 'Lunatic', 'Lurid',
  'Luscious', 'Lush', 'Lustrous', 'Lusty', 'Lying', 'Lymph', 'Lynx', 'Lyric',
  'Macabre', 'Macho', 'Mad', 'Madly', 'Magenta', 'Magic', 'Magnetic', 'Magnificent',
  'Mahogany', 'Maid', 'Mailed', 'Main', 'Majestic', 'Major', 'Making', 'Malice',
  'Mammoth', 'Manic', 'Mannered', 'Mantle', 'Many', 'Marble', 'Marginal', 'Marine',
  'Marked', 'Maroon', 'Married', 'Marshy', 'Martial', 'Marvel', 'Masculine', 'Masked',
  'Massive', 'Master', 'Match', 'Mated', 'Material', 'Maternal', 'Matte', 'Mature',
  'Mauve', 'Maximal', 'Maximum', 'Mazed', 'Meager', 'Mealy', 'Mean', 'Meandering',
  'Meaning', 'Measly', 'Meaty', 'Mechanical', 'Medical', 'Medium', 'Meek', 'Mellow',
  'Melodic', 'Melting', 'Member', 'Membrane', 'Memento', 'Menacing', 'Mental', 'Merciful',
  'Mere', 'Merry', 'Mesh', 'Messy', 'Metal', 'Metallic', 'Meteor', 'Mighty',
  'Mild', 'Milky', 'Mill', 'Mimic', 'Minced', 'Mindful', 'Mini', 'Miniature',
  'Minimal', 'Minimum', 'Minor', 'Mint', 'Minty', 'Minute', 'Mirrored', 'Misty',
  'Mixed', 'Mobile', 'Mocha', 'Mock', 'Moderate', 'Modern', 'Modest', 'Moist',
  'Molten', 'Moment', 'Monarch', 'Monastic', 'Mondo', 'Monied', 'Monkey', 'Mono',
  'Monster', 'Monstrous', 'Monumental', 'Moody', 'Moon', 'Moonlit', 'Morbid', 'Moral',
  'Morning', 'Mortal', 'Mosaic', 'Motherly', 'Motion', 'Mottled', 'Mountain', 'Mournful',
  'Mousy', 'Moving', 'Mown', 'Muddy', 'Muffled', 'Muggy', 'Mulched', 'Multiple',
  'Mundane', 'Mural', 'Murky', 'Muscular', 'Mushy', 'Musical', 'Muted', 'Mutual',
  'Mysterious', 'Mythic', 'Nacreous', 'Naive', 'Naked', 'Narrow', 'Nasty', 'Native',
  'Natural', 'Naughty', 'Nautical', 'Naval', 'Near', 'Neat', 'Nebulous', 'Necessary',
  'Needless', 'Needy', 'Negative', 'Neglected', 'Neighborly', 'Neither', 'Nervous', 'Nested',
  'Net', 'Neural', 'Neutral', 'New', 'Next', 'Nifty', 'Nimble', 'Nippy',
  'Noble', 'Nocturnal', 'Noiseless', 'Noisy', 'Nomadic', 'Nonstop', 'Normal', 'Nostalgic',
  'Notable', 'Noted', 'Novel', 'Nowhere', 'Noxious', 'Nubile', 'Nuclear', 'Nude',
  'Numb', 'Numbered', 'Numerous', 'Nurturing', 'Nutty', 'Oaken', 'Obedient', 'Oblique',
  'Obscure', 'Observant', 'Obsessed', 'Obvious', 'Occult', 'Ocean', 'Ocher', 'Odd',
  'Odorless', 'Offbeat', 'Offensive', 'Official', 'Oily', 'Okay', 'Old', 'Olive',
  'Olympic', 'Ominous', 'One', 'Onion', 'Online', 'Only', 'Onyx', 'Open',
  'Opaque', 'Open', 'Operatic', 'Opinion', 'Opulent', 'Orange', 'Orbital', 'Orchard',
  'Orderly', 'Ordinary', 'Organic', 'Oriental', 'Ornate', 'Orphan', 'Orthodox', 'Oscillating',
  'Other', 'Outback', 'Outdoor', 'Outer', 'Outgoing', 'Outlaw', 'Oval', 'Over',
  'Overall', 'Overcast', 'Overflow', 'Overjoyed', 'Overseas', 'Overt', 'Overweight', 'Overwhelming',
  'Owned', 'Oxygen', 'Pacified', 'Padded', 'Pagan', 'Pained', 'Painted', 'Pale',
  'Paltry', 'Pampered', 'Panic', 'Panoramic', 'Paper', 'Parched', 'Pardon', 'Parental',
  'Parity', 'Partial', 'Particular', 'Partisan', 'Part', 'Passing', 'Passionate', 'Passive',
  'Past', 'Pastel', 'Pastoral', 'Patchy', 'Patent', 'Paternal', 'Patient', 'Patriotic',
  'Patron', 'Pattern', 'Paunchy', 'Paused', 'Peak', 'Peaked', 'Pealing', 'Pearly',
  'Peasant', 'Pebble', 'Peckish', 'Peculiar', 'Pedal', 'Pedantic', 'Peeled', 'Peerless',
  'Pegged', 'Penal', 'Pencil', 'Pending', 'Pent', 'Perfect', 'Period', 'Perky',
  'Permanent', 'Permeable', 'Perplexed', 'Persistent', 'Person', 'Pert', 'Pervasive', 'Petal',
  'Petite', 'Petrified', 'Phantom', 'Phase', 'Phenol', 'Phobic', 'Phony', 'Photon',
  'Physical', 'Piano', 'Picked', 'Pictorial', 'Picture', 'Piebald', 'Piercing', 'Pigmented',
  'Piled', 'Pilgrim', 'Pink', 'Pious', 'Piping', 'Piquant', 'Pirate', 'Pitch',
  'Pithy', 'Pitted', 'Pivotal', 'Pixel', 'Placid', 'Plague', 'Plain', 'Plane',
  'Planned', 'Plastic', 'Plated', 'Platinum', 'Platonic', 'Plausible', 'Playful', 'Pleading',
  'Pleasant', 'Pleased', 'Pleasing', 'Pleated', 'Plentiful', 'Pliant', 'Plodding', 'Plump',
  'Plunging', 'Plush', 'Plushy', 'Pluvial', 'Pneumatic', 'Pocket', 'Poetic', 'Poignant',
  'Pointed', 'Poised', 'Poison', 'Polar', 'Polished', 'Polite', 'Political', 'Polka',
  'Polluted', 'Polo', 'Poly', 'Pompous', 'Pond', 'Pooled', 'Poor', 'Pop',
  'Popular', 'Porcelain', 'Porcine', 'Porous', 'Portable', 'Ported', 'Portly', 'Posed',
  'Positive', 'Postal', 'Poster', 'Potable', 'Potent', 'Potential', 'Potted', 'Powder',
  'Powdery', 'Power', 'Practical', 'Pragmatic', 'Prairie', 'Praise', 'Precious', 'Precise',
  'Predict', 'Prefer', 'Pregnant', 'Premier', 'Premium', 'Prepared', 'Preset', 'Pressed',
  'Pressure', 'Prestige', 'Presumed', 'Pretty', 'Prickly', 'Primal', 'Primary', 'Prime',
  'Primitive', 'Principal', 'Printed', 'Prior', 'Pristine', 'Private', 'Privy', 'Prize',
  'Probable', 'Prodigal', 'Produce', 'Profane', 'Professional', 'Profound', 'Profuse', 'Progressive',
  'Prolific', 'Prominent', 'Promised', 'Prompt', 'Prone', 'Proper', 'Prophetic', 'Prose',
  'Prosperous', 'Protected', 'Protean', 'Proud', 'Proven', 'Prudent', 'Pruned', 'Prussian',
  'Psychedelic', 'Psychic', 'Public', 'Puffed', 'Puffy', 'Pulled', 'Pulp', 'Pulsating',
  'Pumped', 'Punchy', 'Punctual', 'Pungent', 'Punished', 'Puny', 'Pupal', 'Pupil',
  'Pure', 'Purple', 'Purpose', 'Pursued', 'Push', 'Pushy', 'Puzzle', 'Puzzled',
  'Pygmy', 'Pyramid', 'Pyre', 'Quack', 'Quaint', 'Qualified', 'Quantum', 'Quarrel',
  'Quarter', 'Quartz', 'Queasy', 'Queenly', 'Quelled', 'Quenching', 'Queried', 'Question',
  'Quick', 'Quiet', 'Quilted', 'Quinary', 'Quirky', 'Quitting', 'Quivering', 'Quixotic',
  'Quizzical', 'Quota', 'Quoted', 'Racing', 'Radiant', 'Radical', 'Radio', 'Raging',
  'Rainbow', 'Rainy', 'Rambling', 'Rampant', 'Rancid', 'Random', 'Ranged', 'Ranked',
  'Rapid', 'Rapt', 'Rare', 'Raspy', 'Rated', 'Rational', 'Rattan', 'Rattling',
  'Raucous', 'Raven', 'Raw', 'Ray', 'Razor', 'Reactive', 'Ready', 'Real',
  'Reared', 'Rear', 'Reasonable', 'Rebel', 'Reborn', 'Recent', 'Reckless', 'Recycled',
  'Red', 'Reduced', 'Reeking', 'Refined', 'Reflex', 'Reformed', 'Refuge', 'Regal',
  'Regal', 'Regent', 'Regional', 'Regular', 'Relative', 'Relaxed', 'Relentless', 'Relevant',
  'Reliable', 'Relieved', 'Religious', 'Relished', 'Reluctant', 'Remaining', 'Remarkable', 'Remnant',
  'Remote', 'Renal', 'Rendered', 'Renewed', 'Rental', 'Repaid', 'Repeated', 'Repent',
  'Replete', 'Reported', 'Reposed', 'Reproach', 'Reputed', 'Rescued', 'Resent', 'Reserved',
  'Resident', 'Resigned', 'Resilient', 'Resistant', 'Resolute', 'Resonant', 'Respected', 'Responsive',
  'Restful', 'Restless', 'Restored', 'Restrained', 'Result', 'Retail', 'Retired', 'Retreating',
  'Retro', 'Reusable', 'Reviled', 'Revived', 'Revolting', 'Rewarding', 'Rhetoric', 'Rhombic',
  'Rhyming', 'Rhythmic', 'Ribbed', 'Ribald', 'Rich', 'Richer', 'Riding', 'Rife',
  'Rigid', 'Rigorous', 'Riled', 'Rimmed', 'Ringing', 'Rinsed', 'Riot', 'Ripe',
  'Ripened', 'Ripening', 'Rippled', 'Risky', 'Ritual', 'Rival', 'Riveted', 'Roaming',
  'Roaring', 'Roasted', 'Robotic', 'Robust', 'Rocker', 'Rocky', 'Rogue', 'Rolled',
  'Romantic', 'Rookie', 'Room', 'Roomy', 'Rooted', 'Roped', 'Rosy', 'Rotary',
  'Rotating', 'Rotten', 'Rotund', 'Rough', 'Round', 'Rousing', 'Routine', 'Rowdy',
  'Royal', 'Rubber', 'Rubbery', 'Rubicund', 'Ruby', 'Ruddy', 'Rude', 'Ruffled',
  'Rugged', 'Ruined', 'Ruling', 'Rummy', 'Runic', 'Rural', 'Rushing', 'Rustic',
  'Rusty', 'Ruthless', 'Sacred', 'Sad', 'Safe', 'Sage', 'Saintly', 'Salient',
  'Salty', 'Salvaged', 'Same', 'Sanctified', 'Sandy', 'Sane', 'Sanguine', 'Sanitary',
  'Sapphire', 'Sarcastic', 'Sassy', 'Sated', 'Satin', 'Satiny', 'Satirical', 'Satisfied',
  'Saturated', 'Saucy', 'Savage', 'Savant', 'Saved', 'Savory', 'Scandalous', 'Scanned',
  'Scarce', 'Scared', 'Scarlet', 'Scary', 'Scattered', 'Scenic', 'Scented', 'Scheduled',
  'Scholarly', 'Schooled', 'Sciatic', 'Scorched', 'Scoring', 'Scornful', 'Scrambled', 'Scrappy',
  'Scratchy', 'Screaming', 'Screeching', 'Scripted', 'Scrub', 'Scruffy', 'Scrunchy', 'Scrutinized',
  'Scuffed', 'Sculpted', 'Scurrilous', 'Sea', 'Sealed', 'Seamless', 'Seasoned', 'Seated',
  'Secluded', 'Second', 'Secret', 'Sectional', 'Secure', 'Sedate', 'Sedimentary', 'Seductive',
  'Seeing', 'Seeming', 'Segmented', 'Seldom', 'Selected', 'Selective', 'Selfish', 'Selling',
  'Semantic', 'Semi', 'Senatorial', 'Senior', 'Sensational', 'Sensible', 'Sensitive', 'Sensual',
  'Sentient', 'Sentimental', 'Separate', 'Sequential', 'Serene', 'Serial', 'Serious', 'Serpent',
  'Service', 'Serving', 'Session', 'Set', 'Severe', 'Sewn', 'Sexual', 'Shabby',
  'Shadowed', 'Shadowy', 'Shady', 'Shaken', 'Shallow', 'Shame', 'Shaped', 'Shapely',
  'Sharp', 'Shattered', 'Shaved', 'Sheer', 'Sheet', 'Shell', 'Sheltered', 'Shielded',
  'Shifting', 'Shimmering', 'Shining', 'Shiny', 'Shivering', 'Shocked', 'Shoddy', 'Short',
  'Shorter', 'Shrewd', 'Shrieking', 'Shrill', 'Shrinking', 'Shrouded', 'Shrubby', 'Shrunken',
  'Shunned', 'Shut', 'Shy', 'Sick', 'Sickly', 'Sideways', 'Sighing', 'Sightless',
  'Silent', 'Silken', 'Silky', 'Silly', 'Silver', 'Silvery', 'Similar', 'Simple',
  'Sinful', 'Single', 'Singular', 'Sinister', 'Sinking', 'Sinuous', 'Sirius', 'Sisterly',
  'Sitting', 'Situated', 'Sixth', 'Sizeable', 'Sizzling', 'Skeletal', 'Skeptical', 'Sketchy',
  'Skilled', 'Skimpy', 'Skinny', 'Skyward', 'Slack', 'Slain', 'Slanderous', 'Slanted',
  'Slapping', 'Slate', 'Slaty', 'Slaughtered', 'Slavish', 'Sleek', 'Sleeping', 'Sleepless',
  'Sleepy', 'Slender', 'Slick', 'Slight', 'Slim', 'Slimy', 'Slinking', 'Slipshod',
  'Slippery', 'Sloping', 'Sloppy', 'Slothful', 'Slow', 'Sluggish', 'Slumbering', 'Sly',
  'Small', 'Smart', 'Smashing', 'Smelling', 'Smelly', 'Smiling', 'Smoggy', 'Smoking',
  'Smooth', 'Smothering', 'Smug', 'Snapping', 'Snappy', 'Snarling', 'Sneaky', 'Snide',
  'Sniffling', 'Snobbish', 'Snoring', 'Snowy', 'Snug', 'Soaked', 'Soaring', 'Sober',
  'Social', 'Soda', 'Soft', 'Soggy', 'Solar', 'Sold', 'Solid', 'Solitary',
  'Solo', 'Somber', 'Some', 'Sonant', 'Sonic', 'Soothed', 'Sooty', 'Sophisticated',
  'Sordid', 'Sore', 'Sorrowful', 'Sorry', 'Soulful', 'Sound', 'Sour', 'Southern',
  'Souvenir', 'Sovereign', 'Spacious', 'Spangled', 'Spare', 'Sparkling', 'Sparse', 'Spatial',
  'Speaking', 'Special', 'Speckled', 'Speedy', 'Spellbound', 'Spherical', 'Spicy', 'Spiked',
  'Spiky', 'Spilled', 'Spinal', 'Spindly', 'Spinning', 'Spiral', 'Spirited', 'Spiritual',
  'Spiteful', 'Splashing', 'Splendid', 'Splintered', 'Split', 'Spoiled', 'Spoken', 'Spongy',
  'Spontaneous', 'Sporadic', 'Sporting', 'Spotless', 'Spotted', 'Spotty', 'Sprawling', 'Sprayed',
  'Spring', 'Springy', 'Sprouting', 'Spry', 'Spurred', 'Squandered', 'Square', 'Squashed',
  'Squat', 'Squeaky', 'Squealing', 'Squeezed', 'Squinting', 'Squirmy', 'Stable', 'Staccato',
  'Stacked', 'Stained', 'Stainless', 'Stale', 'Stalwart', 'Stamped', 'Standing', 'Starched',
  'Stark', 'Starless', 'Starlit', 'Starred', 'Starry', 'Starting', 'Startled', 'Starving',
  'Stately', 'Static', 'Stationary', 'Statistical', 'Statuary', 'Staunch', 'Steadfast', 'Steady',
  'Stealthy', 'Steaming', 'Steamy', 'Steel', 'Steely', 'Steep', 'Stellar', 'Stem',
  'Stepping', 'Sterile', 'Sterling', 'Sticky', 'Stiff', 'Still', 'Stimulating', 'Stinging',
  'Stingy', 'Stinking', 'Stirring', 'Stitch', 'Stock', 'Stoic', 'Stony', 'Stormy',
  'Stout', 'Strange', 'Strangled', 'Strategic', 'Straw', 'Stray', 'Streaked', 'Streaming',
  'Streamlined', 'Strenuous', 'Stressed', 'Stretch', 'Stricken', 'Strict', 'Strident', 'Striking',
  'Stringent', 'Stripped', 'Stroked', 'Strong', 'Structured', 'Struggling', 'Strumming', 'Studded',
  'Studious', 'Stuffed', 'Stuffy', 'Stumbling', 'Stunned', 'Stunning', 'Stunted', 'Stupid',
  'Sturdy', 'Stuttering', 'Stylish', 'Stylized', 'Suave', 'Sub', 'Subdued', 'Subject',
  'Sublime', 'Submerged', 'Subtle', 'Suburban', 'Succeeding', 'Sudden', 'Suffering', 'Sugary',
  'Suitable', 'Sullen', 'Sulphur', 'Sultry', 'Summary', 'Summer', 'Summery', 'Sumptuous',
  'Sunlit', 'Sunny', 'Sunrise', 'Sunset', 'Super', 'Superb', 'Superficial', 'Superior',
  'Supple', 'Supplied', 'Supreme', 'Sure', 'Surging', 'Surly', 'Surreal', 'Surrounded',
  'Surviving', 'Suspected', 'Suspended', 'Suspicious', 'Swampy', 'Swanky', 'Sweaty', 'Sweeping',
  'Sweet', 'Swelled', 'Sweltering', 'Swift', 'Swimming', 'Swirling', 'Swooping', 'Sword',
  'Syllabic', 'Sylvan', 'Symbolic', 'Sympathetic', 'Symphonic', 'Symptomatic', 'Synaptic', 'Syndicated',
  'Synergistic', 'Synthetic', 'Systematic', 'Taboo', 'Tacit', 'Tacky', 'Tactful', 'Tactical',
  'Tainted', 'Taking', 'Talented', 'Talking', 'Tall', 'Tame', 'Tan', 'Tangible',
  'Tangled', 'Tangy', 'Tanned', 'Tantalizing', 'Tapered', 'Tardy', 'Targeted', 'Tarnished',
  'Tart', 'Tasteful', 'Tasteless', 'Tasty', 'Tattered', 'Taunting', 'Taut', 'Tawdry',
  'Taxing', 'Teachable', 'Teary', 'Teasing', 'Technical', 'Tedious', 'Teeming', 'Telling',
  'Tempered', 'Temporal', 'Tempting', 'Tenacious', 'Tender', 'Tense', 'Tentative', 'Tepid',
  'Terminal', 'Terrific', 'Terrified', 'Terrifying', 'Tested', 'Testy', 'Thankful', 'Thawed',
  'Theatrical', 'Thematic', 'Thermal', 'Thick', 'Thin', 'Thirsty', 'Thorny', 'Thorough',
  'Thoughtful', 'Thoughtless', 'Thrashing', 'Threadbare', 'Threatening', 'Thrilling', 'Thriving', 'Throbbing',
  'Throbbing', 'Throned', 'Thronged', 'Through', 'Thumb', 'Thumping', 'Thunder', 'Thundering',
  'Ticked', 'Ticking', 'Tidal', 'Tidy', 'Tiered', 'Tight', 'Till', 'Timbered',
  'Timeless', 'Timely', 'Timid', 'Tingling', 'Tinkling', 'Tinted', 'Tiny', 'Tipped',
  'Tired', 'Tireless', 'Tiresome', 'Titanium', 'Titular', 'Today', 'Toiling', 'Tolerable',
  'Tolerant', 'Tolling', 'Tom', 'Tonal', 'Toned', 'Toothsome', 'Top', 'Topical',
  'Toppled', 'Torched', 'Tormenting', 'Torn', 'Torrid', 'Tortured', 'Total', 'Totemic',
  'Touching', 'Tough', 'Touristy', 'Towering', 'Toxic', 'Toy', 'Traced', 'Tracked',
  'Traded', 'Traditional', 'Traffic', 'Tragic', 'Trailing', 'Trained', 'Traitorous', 'Tranquil',
  'Transient', 'Translucent', 'Transparent', 'Trapped', 'Trashy', 'Traumatic', 'Traveled', 'Treacherous',
  'Treasured', 'Treated', 'Treble', 'Trembling', 'Tremendous', 'Trenchant', 'Trendy', 'Trial',
  'Tribal', 'Trick', 'Trickling', 'Trifling', 'Trim', 'Triple', 'Triumphant', 'Trivial',
  'Tropical', 'Troubled', 'Troublesome', 'True', 'Trusting', 'Trustworthy', 'Trusty', 'Truthful',
  'Trying', 'Tubular', 'Tucked', 'Tuff', 'Tufted', 'Tumbling', 'Tumultuous', 'Tuned',
  'Turbid', 'Turbulent', 'Turf', 'Turquoise', 'Tusked', 'Tutored', 'Twin', 'Twinkling',
  'Twirling', 'Twisted', 'Twitching', 'Twittering', 'Twofold', 'Typecast', 'Typical', 'Tyrannical',
  'Ubiquitous', 'Ugly', 'Ulterior', 'Ultimate', 'Ultra', 'Unable', 'Unaware', 'Unbroken',
  'Uncanny', 'Uncertain', 'Uncommon', 'Unconscious', 'Uncouth', 'Uncut', 'Under', 'Underdog',
  'Underground', 'Underhand', 'Underlined', 'Undermined', 'Understood', 'Undeserved', 'Undying', 'Uneasy',
  'Unending', 'Unequal', 'Uneven', 'Unexpected', 'Unfair', 'Unfaithful', 'Unfamiliar', 'Unfastened',
  'Unfavorable', 'Unfeeling', 'Unfettered', 'Unfinished', 'Unfit', 'Unforeseen', 'Unforgettable', 'Unfortunate',
  'Unfriendly', 'Unfurled', 'Ungainly', 'Ungodly', 'Unguarded', 'Unhappy', 'Unharmed', 'Unhealthy',
  'Unheard', 'Unhinged', 'Unholy', 'Unhurt', 'Uniform', 'Unilateral', 'Unimaginable', 'Unimportant',
  'Uninspired', 'Unintended', 'Uninvited', 'Unique', 'Unison', 'United', 'Universal', 'Unknown',
  'Unlawful', 'Unleashed', 'Unlikely', 'Unlimited', 'Unlocked', 'Unloved', 'Unlucky', 'Unnatural',
  'Unnecessary', 'Unnoticed', 'Unobserved', 'Unobtrusive', 'Unpaid', 'Unplanned', 'Unpleasant', 'Unpopular',
  'Unprecedented', 'Unpredictable', 'Unprepared', 'Unproductive', 'Unprotected', 'Unpublished', 'Unqualified', 'Unquenchable',
  'Unquestioned', 'Unraveled', 'Unreal', 'Unreasonable', 'Unrecognized', 'Unrelated', 'Unreleased', 'Unreliable',
  'Unrepentant', 'Unresolved', 'Unrest', 'Unrivaled', 'Unruly', 'Unsafe', 'Unsavory', 'Unscathed',
  'Unscripted', 'Unsealed', 'Unseen', 'Unselfish', 'Unsettled', 'Unshackled', 'Unshaken', 'Unsightly',
  'Unskilled', 'Unsolved', 'Unsound', 'Unspoken', 'Unstable', 'Unsteady', 'Unstoppable', 'Unstructured',
  'Unsuccessful', 'Unsuitable', 'Untamed', 'Untapped', 'Untested', 'Untethered', 'Unthinkable', 'Untidy',
  'Untold', 'Untouched', 'Untrained', 'Untried', 'Untrue', 'Unusual', 'Unveiled', 'Unwanted',
  'Unwary', 'Unwashed', 'Unwelcome', 'Unwell', 'Unwieldy', 'Unwilling', 'Unwise', 'Unwitting',
  'Unworthy', 'Unwritten', 'Upbeat', 'Uphill', 'Uphold', 'Upland', 'Uplifted', 'Uplifting',
  'Upper', 'Uppity', 'Upright', 'Uproarious', 'Uprooted', 'Upset', 'Upside', 'Upstage',
  'Upstart', 'Upstream', 'Upward', 'Urban', 'Urbane', 'Urgent', 'Ursine', 'Usable',
  'Used', 'Useful', 'Useless', 'Usual', 'Utmost', 'Utopian', 'Utter', 'Uttered',
  'Vacant', 'Vaccinated', 'Vague', 'Vain', 'Valiant', 'Valid', 'Valuable', 'Valued',
  'Vanilla', 'Vapid', 'Vapor', 'Variable', 'Varied', 'Vast', 'Vaulted', 'Vegan',
  'Vegetable', 'Vehement', 'Velvety', 'Vendored', 'Venerable', 'Vengeful', 'Venomous', 'Ventilated',
  'Verbal', 'Verbose', 'Verdant', 'Verified', 'Versatile', 'Versed', 'Vertical', 'Vexed',
  'Vibrant', 'Vibrating', 'Vicious', 'Victorious', 'Video', 'Vigilant', 'Vigorous', 'Vile',
  'Villainous', 'Vindicated', 'Violent', 'Violet', 'Virtual', 'Virtuous', 'Virulent', 'Viscous',
  'Visible', 'Visionary', 'Visual', 'Vital', 'Vivacious', 'Vivid', 'Vocal', 'Vocalic',
  'Vocational', 'Voiceless', 'Volatile', 'Volcanic', 'Voltaic', 'Voluminous', 'Voluntary', 'Voluptuous',
  'Vulgar', 'Vulnerable', 'Wacky', 'Wafting', 'Wage', 'Wailing', 'Waiting', 'Wakeful',
  'Waking', 'Walking', 'Wandering', 'Wanted', 'War', 'Warlike', 'Warm', 'Warming',
  'Warning', 'Warped', 'Wary', 'Washed', 'Wasteful', 'Watchful', 'Watery', 'Wavy',
  'Waxen', 'Waxy', 'Weak', 'Wealthy', 'Weapon', 'Wearing', 'Weary', 'Weathered',
  'Weaving', 'Webbed', 'Wedded', 'Weekly', 'Weighted', 'Weightless', 'Weighty', 'Weird',
  'Welcome', 'Welcoming', 'Well', 'Welsh', 'Wet', 'Whimsical', 'Whirling', 'Whispering',
  'White', 'Whole', 'Wholesale', 'Wholesome', 'Wicked', 'Wide', 'Widespread', 'Wielded',
  'Wild', 'Willing', 'Willowy', 'Wily', 'Winding', 'Windy', 'Winged', 'Winking',
  'Winning', 'Wintry', 'Wiry', 'Wise', 'Wishful', 'Wispy', 'Wistful', 'Witch',
  'Withdrawn', 'Withering', 'Within', 'Witness', 'Witty', 'Wizard', 'Woeful', 'Wolflike',
  'Womanly', 'Wonder', 'Wonderful', 'Wondrous', 'Wooden', 'Woodsy', 'Woozy', 'Wordless',
  'Wordy', 'Working', 'World', 'Worldly', 'Worn', 'Worried', 'Worrying', 'Worse',
  'Worshipful', 'Worst', 'Worth', 'Worthless', 'Worthy', 'Woven', 'Wounded', 'Woven',
  'Wracking', 'Wrathful', 'Wrenching', 'Wretched', 'Wrinkled', 'Wrinkly', 'Wrist', 'Writ',
  'Written', 'Wrong', 'Wry', 'Yawning', 'Yearly', 'Yearning', 'Yellow', 'Yellowed',
  'Yielding', 'Young', 'Younger', 'Youthful', 'Zany', 'Zealous', 'Zen', 'Zesty',
  'Zigzag', 'Zillion', 'Zinc', 'Zippy', 'Zonal', 'Zoned', 'Zooming', 'Zygote',
];

const nouns = [
  'Ant', 'Ape', 'Axe', 'Badger', 'Bear', 'Beaver', 'Bee', 'Bird',
  'Boar', 'Boa', 'Bug', 'Bull', 'Bunny', 'Camel', 'Cat', 'Clam',
  'Cobra', 'Crab', 'Crane', 'Cricket', 'Crow', 'Deer', 'Dodo', 'Dog',
  'Dolphin', 'Donkey', 'Dove', 'Dragon', 'Duck', 'Eagle', 'Eel', 'Elk',
  'Emu', 'Falcon', 'Ferret', 'Finch', 'Fish', 'Fly', 'Fox', 'Frog',
  'Gecko', 'Giraffe', 'Gnat', 'Goat', 'Goose', 'Gorilla', 'Gull', 'Hare',
  'Hawk', 'Hen', 'Heron', 'Horse', 'Hyena', 'Impala', 'Jay', 'Jelly',
  'Kiwi', 'Koala', 'Koi', 'Lamb', 'Lark', 'Lemur', 'Leopard', 'Lion',
  'Llama', 'Lobster', 'Lynx', 'Mantis', 'Mole', 'Monkey', 'Moose', 'Moth',
  'Mouse', 'Mule', 'Newt', 'Ocelot', 'Orca', 'Otter', 'Owl', 'Panda',
  'Parrot', 'Peacock', 'Pelican', 'Penguin', 'Pigeon', 'Pony', 'Puma', 'Puppy',
  'Rabbit', 'Raccoon', 'Ram', 'Rat', 'Raven', 'Robin', 'Sable', 'Salmon',
  'Seal', 'Shark', 'Sheep', 'Shrew', 'Shrimp', 'Skunk', 'Sloth', 'Snail',
  'Snake', 'Sparrow', 'Spider', 'Squid', 'Squirrel', 'Starling', 'Stork', 'Swan',
  'Tiger', 'Toad', 'Trout', 'Turkey', 'Turtle', 'Viper', 'Vole', 'Vulture',
  'Wallaby', 'Walrus', 'Wasp', 'Weasel', 'Whale', 'Wolf', 'Wombat', 'Wren',
  'Yak', 'Zebra', 'Acorn', 'Amber', 'Apple', 'Ash', 'Atlas', 'Aurora',
  'Axe', 'Bacon', 'Badge', 'Bamboo', 'Basalt', 'Basin', 'Basket', 'Batch',
  'Bazaar', 'Beacon', 'Beam', 'Bean', 'Beard', 'Beast', 'Bed', 'Beetle',
  'Belt', 'Bench', 'Biscuit', 'Blade', 'Blanket', 'Blaze', 'Bleach', 'Blend',
  'Blimp', 'Blob', 'Block', 'Bloom', 'Blossom', 'Blouse', 'Bluff', 'Blur',
  'Board', 'Boat', 'Bolt', 'Bomb', 'Bone', 'Book', 'Boom', 'Boot',
  'Bottle', 'Boulder', 'Bounce', 'Bow', 'Bowl', 'Box', 'Brain', 'Bramble',
  'Branch', 'Bread', 'Breeze', 'Brick', 'Bridge', 'Bristle', 'Broccoli', 'Brook',
  'Broom', 'Brush', 'Bubble', 'Bucket', 'Bud', 'Buddy', 'Buffalo', 'Bug',
  'Bulb', 'Bulge', 'Bulk', 'Bullet', 'Bump', 'Bun', 'Bunch', 'Burden',
  'Burrow', 'Burst', 'Bush', 'Butter', 'Button', 'Cabbage', 'Cabin', 'Cable',
  'Cactus', 'Cage', 'Cake', 'Canvas', 'Canyon', 'Cap', 'Cape', 'Car',
  'Card', 'Cargo', 'Carpet', 'Carrot', 'Cascade', 'Case', 'Cash', 'Castle',
  'Cave', 'Cedar', 'Cell', 'Cello', 'Cement', 'Center', 'Chain', 'Chair',
  'Chalk', 'Chamber', 'Chaos', 'Charm', 'Chart', 'Cheek', 'Cheese', 'Cherry',
  'Chest', 'Chime', 'Chip', 'Chisel', 'Chocolate', 'Chord', 'Chunk', 'Circuit',
  'City', 'Clap', 'Clay', 'Cliff', 'Climate', 'Climb', 'Clock', 'Cloud',
  'Clover', 'Club', 'Coast', 'Coat', 'Cobble', 'Cocoa', 'Code', 'Coil',
  'Coin', 'Collar', 'Color', 'Column', 'Comb', 'Comet', 'Compass', 'Cone',
  'Coral', 'Cord', 'Core', 'Cork', 'Cotton', 'Couch', 'Cough', 'Count',
  'Course', 'Court', 'Cove', 'Crack', 'Craft', 'Crane', 'Crash', 'Crater',
  'Crawl', 'Cream', 'Creek', 'Crest', 'Cricket', 'Crop', 'Cross', 'Crowd',
  'Crown', 'Crumb', 'Crush', 'Crust', 'Crystal', 'Cube', 'Cult', 'Cup',
  'Curb', 'Cure', 'Curio', 'Curve', 'Cushion', 'Cycle', 'Dale', 'Dance',
  'Dart', 'Dash', 'Data', 'Dawn', 'Day', 'Deal', 'Debt', 'Deck',
  'Decoy', 'Degree', 'Delay', 'Dent', 'Depth', 'Desert', 'Desk', 'Device',
  'Dew', 'Dial', 'Diamond', 'Diary', 'Dice', 'Dig', 'Dime', 'Dinner',
  'Dinosaur', 'Diploma', 'Disk', 'Ditch', 'Dock', 'Doctor', 'Dogma', 'Doll',
  'Domain', 'Door', 'Dose', 'Dot', 'Doubt', 'Dough', 'Dove', 'Draft',
  'Dragon', 'Drain', 'Drama', 'Drape', 'Draw', 'Dress', 'Drift', 'Drill',
  'Drink', 'Drip', 'Drive', 'Drop', 'Drought', 'Drum', 'Duck', 'Dune',
  'Dusk', 'Dust', 'Dye', 'Dynasty', 'Eagle', 'Ear', 'Earth', 'Ease',
  'East', 'Echo', 'Eclipse', 'Edge', 'Eel', 'Effect', 'Egg', 'Elbow',
  'Elf', 'Elm', 'Ember', 'Emerald', 'Empire', 'End', 'Energy', 'Engine',
  'Epoch', 'Equal', 'Equator', 'Era', 'Error', 'Estate', 'Ether', 'Event',
  'Evergreen', 'Evidence', 'Evil', 'Exam', 'Excess', 'Exile', 'Exit', 'Expand',
  'Expert', 'Exploit', 'Export', 'Extent', 'Eye', 'Fabric', 'Face', 'Fact',
  'Fade', 'Fairy', 'Faith', 'Fake', 'Fall', 'Fame', 'Fan', 'Fang',
  'Farm', 'Fashion', 'Fate', 'Fault', 'Fear', 'Feast', 'Feather', 'Feature',
  'Fence', 'Fern', 'Fever', 'Fiber', 'Field', 'Fighter', 'File', 'Film',
  'Filter', 'Fin', 'Finance', 'Find', 'Finger', 'Fire', 'Firm', 'Fish',
  'Fist', 'Fit', 'Fix', 'Flag', 'Flame', 'Flash', 'Flask', 'Flaw',
  'Fleet', 'Flesh', 'Flight', 'Fling', 'Flint', 'Flipper', 'Float', 'Flock',
  'Flood', 'Floor', 'Flour', 'Flow', 'Flower', 'Flute', 'Flux', 'Fly',
  'Foam', 'Focus', 'Fog', 'Foil', 'Fold', 'Food', 'Foot', 'Force',
  'Forest', 'Fork', 'Form', 'Fort', 'Fortune', 'Fossil', 'Fountain', 'Fowl',
  'Frame', 'Frenzy', 'Friction', 'Fridge', 'Friend', 'Fright', 'Fringe', 'Frog',
  'Front', 'Frost', 'Frown', 'Fruit', 'Fuel', 'Fugue', 'Fume', 'Fun',
  'Fund', 'Fury', 'Fuse', 'Fuzz', 'Gadget', 'Gain', 'Galaxy', 'Gale',
  'Gall', 'Game', 'Gap', 'Garage', 'Garden', 'Garlic', 'Gas', 'Gate',
  'Gauge', 'Gear', 'Gem', 'Gender', 'Genius', 'Ghost', 'Gift', 'Gig',
  'Giraffe', 'Gist', 'Glacier', 'Glade', 'Glare', 'Glass', 'Glee', 'Glide',
  'Globe', 'Gloom', 'Glory', 'Gloss', 'Glove', 'Glow', 'Glue', 'Goal',
  'Goat', 'Gold', 'Golf', 'Good', 'Goose', 'Gorge', 'Gossip', 'Grain',
  'Grand', 'Grape', 'Graph', 'Grasp', 'Grass', 'Grate', 'Grave', 'Gravel',
  'Grease', 'Great', 'Greed', 'Green', 'Grid', 'Grief', 'Grill', 'Grime',
  'Grind', 'Grip', 'Grit', 'Groan', 'Grocery', 'Groove', 'Ground', 'Group',
  'Grove', 'Growth', 'Grudge', 'Guard', 'Guess', 'Guest', 'Guide', 'Guild',
  'Guilt', 'Gulf', 'Gum', 'Gun', 'Gush', 'Gust', 'Gutter', 'Gym',
  'Habitat', 'Hail', 'Hair', 'Half', 'Hall', 'Halogen', 'Hammer', 'Hand',
  'Handle', 'Harbor', 'Hard', 'Harp', 'Harsh', 'Harvest', 'Hash', 'Haste',
  'Hat', 'Hatch', 'Haunt', 'Haven', 'Hawk', 'Haze', 'Hazel', 'Head',
  'Health', 'Hearth', 'Heart', 'Heat', 'Heaven', 'Heavy', 'Hedge', 'Heel',
  'Height', 'Heist', 'Helix', 'Hell', 'Helm', 'Help', 'Hem', 'Herb',
  'Herd', 'Here', 'Hero', 'Hickory', 'Hide', 'High', 'Hill', 'Hilt',
  'Hint', 'Hip', 'Hiss', 'Hive', 'Hobby', 'Hockey', 'Hog', 'Hold',
  'Hole', 'Hollow', 'Home', 'Honey', 'Honor', 'Hood', 'Hook', 'Hope',
  'Horizon', 'Horn', 'Horse', 'Hose', 'Hospital', 'Host', 'Hotel', 'Hound',
  'Hour', 'House', 'Hub', 'Hue', 'Hug', 'Hull', 'Human', 'Humor',
  'Hunter', 'Hurdle', 'Hurricane', 'Hurry', 'Hurt', 'Husband', 'Hut', 'Hydra',
  'Ice', 'Idea', 'Image', 'Impact', 'Impulse', 'Index', 'Indigo', 'Infant',
  'Inferno', 'Ink', 'Inlay', 'Inlet', 'Insect', 'Insert', 'Inside', 'Insight',
  'Instinct', 'Insult', 'Intent', 'Interval', 'Intrigue', 'Invite', 'Iron', 'Island',
  'Isle', 'Ivory', 'Jack', 'Jade', 'Jaguar', 'Jam', 'Jar', 'Java',
  'Jaw', 'Jazz', 'Jeans', 'Jelly', 'Jet', 'Jewel', 'Job', 'Joke',
  'Journal', 'Journey', 'Joy', 'Judge', 'Juice', 'Jungle', 'Junior', 'Junk',
  'Jury', 'Justice', 'Karma', 'Kayak', 'Kazoo', 'Keen', 'Keep', 'Kelp',
  'Kernel', 'Kettle', 'Key', 'Kid', 'Kilo', 'Kind', 'King', 'Kiss',
  'Kit', 'Kitchen', 'Kite', 'Kitten', 'Kiwi', 'Knack', 'Knee', 'Knit',
  'Knob', 'Knock', 'Knot', 'Know', 'Koala', 'Label', 'Labor', 'Lace',
  'Lack', 'Ladder', 'Ladle', 'Lagoon', 'Lake', 'Lamb', 'Lamp', 'Land',
  'Lane', 'Language', 'Lap', 'Laptop', 'Lark', 'Laser', 'Last', 'Latch',
  'Late', 'Laugh', 'Launch', 'Lava', 'Lawn', 'Lawsuit', 'Layer', 'Layout',
  'Lazy', 'Lead', 'Leaf', 'League', 'Leak', 'Lean', 'Leap', 'Learn',
  'Lease', 'Leather', 'Leave', 'Lecture', 'Leg', 'Legacy', 'Legend', 'Leisure',
  'Lemon', 'Length', 'Lens', 'Leopard', 'Lesson', 'Letter', 'Level', 'Lever',
  'Lexicon', 'Liar', 'Liberty', 'Library', 'License', 'Lid', 'Life', 'Lift',
  'Light', 'Like', 'Lilac', 'Lily', 'Limb', 'Lime', 'Limit', 'Line',
  'Linen', 'Liner', 'Link', 'Lion', 'Lip', 'Liquid', 'List', 'Listen',
  'Litter', 'Little', 'Live', 'Lizard', 'Llama', 'Load', 'Loaf', 'Loan',
  'Lobby', 'Lobster', 'Local', 'Lock', 'Locust', 'Loft', 'Log', 'Logic',
  'Lone', 'Look', 'Loop', 'Loose', 'Loot', 'Lord', 'Lore', 'Loss',
  'Lost', 'Lot', 'Lotion', 'Lottery', 'Loud', 'Love', 'Lover', 'Low',
  'Loyal', 'Luck', 'Luggage', 'Lumber', 'Lunar', 'Lunch', 'Lung', 'Lure',
  'Lurk', 'Lush', 'Lust', 'Luxury', 'Lymph', 'Lynx', 'Lyric', 'Macaw',
  'Machine', 'Mad', 'Magic', 'Magnet', 'Magnolia', 'Mail', 'Main', 'Major',
  'Mammal', 'Mansion', 'Mantle', 'Map', 'Maple', 'Marble', 'March', 'Margin',
  'Marina', 'Mark', 'Market', 'Marsh', 'Mason', 'Mass', 'Master', 'Match',
  'Mate', 'Matter', 'Meadow', 'Meal', 'Mean', 'Measure', 'Meat', 'Mechanic',
  'Medal', 'Media', 'Medicine', 'Medium', 'Melody', 'Melt', 'Member', 'Memory',
  'Menu', 'Mercy', 'Merge', 'Merit', 'Mesh', 'Mess', 'Metal', 'Meteor',
  'Method', 'Meter', 'Might', 'Mile', 'Milk', 'Mill', 'Mimic', 'Mind',
  'Mine', 'Mini', 'Mint', 'Minute', 'Mirage', 'Mirror', 'Mist', 'Mitten',
  'Mix', 'Mixture', 'Moat', 'Mobile', 'Mob', 'Mock', 'Mode', 'Model',
  'Moment', 'Money', 'Monitor', 'Monk', 'Monkey', 'Monster', 'Month', 'Monument',
  'Mood', 'Moon', 'Moor', 'Moose', 'Mop', 'Moral', 'Morning', 'Mortar',
  'Mosaic', 'Mosquito', 'Moss', 'Moth', 'Mother', 'Motion', 'Motor', 'Mound',
  'Mount', 'Mountain', 'Mouse', 'Mouth', 'Move', 'Movie', 'Mud', 'Mug',
  'Mule', 'Mural', 'Muscle', 'Museum', 'Mushroom', 'Music', 'Musk', 'Must',
  'Mute', 'Mystery', 'Myth', 'Nail', 'Name', 'Nap', 'Narrative', 'Narrow',
  'Nation', 'Nature', 'Nausea', 'Navy', 'Neck', 'Need', 'Needle', 'Neon',
  'Nerve', 'Nest', 'Net', 'Network', 'Neuron', 'Neutral', 'New', 'News',
  'Next', 'Nice', 'Night', 'Nimble', 'Nine', 'Nirvana', 'Node', 'Noise',
  'Nomad', 'None', 'Noodle', 'Noon', 'Norm', 'North', 'Nose', 'Note',
  'Nothing', 'Notice', 'Notion', 'Noun', 'Novel', 'Now', 'Nucleus', 'Nude',
  'Number', 'Nurse', 'Nut', 'Nylon', 'Oak', 'Oasis', 'Oath', 'Obedience',
  'Obelisk', 'Object', 'Oblivion', 'Obscure', 'Observe', 'Obsidian', 'Ocean', 'Ocelot',
  'Octave', 'Odometer', 'Odyssey', 'Offer', 'Office', 'Oil', 'Olive', 'Omen',
  'Onion', 'Online', 'Opal', 'Open', 'Opera', 'Opinion', 'Opium', 'Opt',
  'Oracle', 'Orange', 'Orbit', 'Orchard', 'Order', 'Ore', 'Organ', 'Origin',
  'Ornament', 'Oscillator', 'Osmosis', 'Osprey', 'Otter', 'Outcome', 'Outer', 'Outlet',
  'Output', 'Outset', 'Oven', 'Over', 'Owl', 'Owner', 'Oxide', 'Oxygen',
  'Oyster', 'Ozone', 'Pace', 'Pack', 'Packet', 'Pad', 'Page', 'Pain',
  'Paint', 'Pair', 'Palace', 'Palm', 'Pan', 'Panda', 'Panel', 'Panic',
  'Panther', 'Paper', 'Parade', 'Paradox', 'Paragraph', 'Parallel', 'Parasol', 'Parent',
  'Parish', 'Park', 'Parrot', 'Part', 'Party', 'Pass', 'Passion', 'Past',
  'Pasta', 'Paste', 'Pasture', 'Patch', 'Path', 'Patience', 'Patient', 'Patrol',
  'Pattern', 'Pause', 'Pavement', 'Paw', 'Pay', 'Peace', 'Peach', 'Peak',
  'Peanut', 'Pear', 'Pearl', 'Peel', 'Peer', 'Pelican', 'Pen', 'Penalty',
  'Pencil', 'Penguin', 'Peninsula', 'Penny', 'People', 'Pepper', 'Percent', 'Period',
  'Permit', 'Person', 'Petal', 'Petition', 'Petrol', 'Phase', 'Phenomenon', 'Philosopher',
  'Phoenix', 'Phone', 'Photo', 'Phrase', 'Piano', 'Pick', 'Picture', 'Pie',
  'Piece', 'Pig', 'Pigeon', 'Pile', 'Pillar', 'Pillow', 'Pilot', 'Pin',
  'Pine', 'Pink', 'Pioneer', 'Pipe', 'Pirate', 'Piston', 'Pit', 'Pitch',
  'Pity', 'Pixel', 'Pizza', 'Place', 'Plague', 'Plain', 'Plan', 'Plane',
  'Planet', 'Plant', 'Plasma', 'Plaster', 'Plastic', 'Plate', 'Platinum', 'Play',
  'Plea', 'Pleasure', 'Plenty', 'Plier', 'Plow', 'Plug', 'Plum', 'Plumber',
  'Plume', 'Plunge', 'Pocket', 'Poem', 'Poet', 'Point', 'Poison', 'Poker',
  'Polar', 'Pole', 'Policy', 'Polio', 'Pollen', 'Polymer', 'Pond', 'Pony',
  'Pool', 'Pop', 'Popcorn', 'Poppy', 'Popular', 'Porch', 'Porcupine', 'Port',
  'Portrait', 'Pose', 'Position', 'Post', 'Posture', 'Pot', 'Potato', 'Potential',
  'Pound', 'Pour', 'Powder', 'Power', 'Practice', 'Prairie', 'Praise', 'Prawn',
  'Prayer', 'Preacher', 'Precedent', 'Precision', 'Predator', 'Preface', 'Pregnancy', 'Premise',
  'Premium', 'Prescription', 'Present', 'President', 'Press', 'Pressure', 'Prestige', 'Preview',
  'Price', 'Pride', 'Priest', 'Prime', 'Prince', 'Princess', 'Principle', 'Print',
  'Prism', 'Prison', 'Privacy', 'Prize', 'Problem', 'Process', 'Produce', 'Product',
  'Profit', 'Program', 'Project', 'Promise', 'Promotion', 'Prompt', 'Proof', 'Prophet',
  'Proposal', 'Prose', 'Prospect', 'Protection', 'Protein', 'Protest', 'Protocol', 'Proud',
  'Proverb', 'Province', 'Proxy', 'Psalm', 'Pulse', 'Pump', 'Pumpkin', 'Punch',
  'Punishment', 'Pupil', 'Puppet', 'Puppy', 'Purchase', 'Purple', 'Purpose', 'Purse',
  'Pursuit', 'Push', 'Puzzle', 'Pyramid', 'Python', 'Quail', 'Quality', 'Quantity',
  'Quarry', 'Quarter', 'Quartz', 'Queen', 'Query', 'Quest', 'Question', 'Queue',
  'Quick', 'Quiet', 'Quill', 'Quilt', 'Quirk', 'Quiver', 'Rabbit', 'Raccoon',
  'Race', 'Rack', 'Radar', 'Radiation', 'Radio', 'Radish', 'Radius', 'Rage',
  'Raid', 'Rail', 'Rain', 'Rainbow', 'Raise', 'Rally', 'Ram', 'Ramble',
  'Ranch', 'Range', 'Rank', 'Rant', 'Rap', 'Rape', 'Rapid', 'Rare',
  'Rash', 'Raspberry', 'Rat', 'Rate', 'Ratio', 'Ration', 'Rattle', 'Raven',
  'Raw', 'Ray', 'Razor', 'Reach', 'Reaction', 'Read', 'Reality', 'Realm',
  'Reap', 'Rear', 'Reason', 'Rebel', 'Receipt', 'Recess', 'Record', 'Recovery',
  'Red', 'Reed', 'Reef', 'Referee', 'Reference', 'Reflect', 'Reform', 'Refuge',
  'Refusal', 'Region', 'Register', 'Regret', 'Regular', 'Reign', 'Reject', 'Relate',
  'Relay', 'Release', 'Relic', 'Relief', 'Religion', 'Remedy', 'Remnant', 'Remote',
  'Rental', 'Repair', 'Repeat', 'Reply', 'Report', 'Reproach', 'Republic', 'Repulse',
  'Request', 'Rescue', 'Research', 'Reserve', 'Resident', 'Resign', 'Resist', 'Resolve',
  'Resort', 'Resource', 'Respect', 'Rest', 'Result', 'Retail', 'Retreat', 'Return',
  'Reunion', 'Reveal', 'Revenge', 'Revenue', 'Reverse', 'Review', 'Revival', 'Revolt',
  'Reward', 'Rhapsody', 'Rhetoric', 'Rhino', 'Rhyme', 'Rhythm', 'Rib', 'Ribbon',
  'Rice', 'Riddle', 'Ride', 'Ridge', 'Rifle', 'Right', 'Rigid', 'Ring',
  'Riot', 'Rip', 'Ripple', 'Rise', 'Risk', 'Ritual', 'Rival', 'River',
  'Road', 'Roar', 'Roast', 'Robbery', 'Robe', 'Robin', 'Robot', 'Rock',
  'Rocket', 'Rod', 'Role', 'Roll', 'Roof', 'Room', 'Root', 'Rope',
  'Rose', 'Rot', 'Rough', 'Round', 'Route', 'Row', 'Rover', 'Royal',
  'Rubber', 'Rubble', 'Ruby', 'Rug', 'Rugby', 'Ruler', 'Rumor', 'Run',
  'Rune', 'Rush', 'Rust', 'Rye', 'Sable', 'Sabre', 'Sack', 'Saddle',
  'Safe', 'Safety', 'Sage', 'Sail', 'Saint', 'Salad', 'Salary', 'Sale',
  'Salmon', 'Salt', 'Salute', 'Sample', 'Sanctuary', 'Sand', 'Sandal', 'Sapphire',
  'Satellite', 'Satire', 'Satisfaction', 'Sauce', 'Sauna', 'Sausage', 'Savannah', 'Scale',
  'Scan', 'Scar', 'Scare', 'Scarf', 'Scene', 'Scent', 'Schedule', 'Scheme',
  'Scholar', 'School', 'Science', 'Scissors', 'Scoop', 'Scope', 'Score', 'Scorn',
  'Scout', 'Scramble', 'Scrap', 'Screen', 'Screw', 'Script', 'Scroll', 'Scrub',
  'Sculpture', 'Sea', 'Seal', 'Search', 'Season', 'Seat', 'Second', 'Secret',
  'Section', 'Security', 'Seed', 'Seek', 'Segment', 'Select', 'Self', 'Senate',
  'Send', 'Sense', 'Sentence', 'Sequence', 'Series', 'Service', 'Session', 'Set',
  'Settle', 'Setup', 'Seventh', 'Shade', 'Shadow', 'Shaft', 'Shake', 'Shall',
  'Shame', 'Shape', 'Share', 'Shark', 'Sharp', 'Shave', 'Shed', 'Sheep',
  'Sheet', 'Shelf', 'Shell', 'Shelter', 'Shield', 'Shift', 'Shine', 'Ship',
  'Shirt', 'Shock', 'Shoe', 'Shoot', 'Shop', 'Shore', 'Short', 'Shot',
  'Shoulder', 'Shout', 'Shovel', 'Show', 'Shower', 'Shred', 'Shrimp', 'Shrine',
  'Shrub', 'Shrug', 'Shudder', 'Shuffle', 'Shut', 'Shy', 'Sibling', 'Sick',
  'Side', 'Siege', 'Sigh', 'Sight', 'Sign', 'Signal', 'Silence', 'Silk',
  'Silly', 'Silver', 'Similar', 'Simple', 'Sin', 'Singer', 'Single', 'Sink',
  'Sir', 'Sister', 'Sit', 'Site', 'Size', 'Skate', 'Skeleton', 'Sketch',
  'Skill', 'Skin', 'Skip', 'Skirt', 'Skull', 'Sky', 'Slab', 'Slack',
  'Slang', 'Slap', 'Slate', 'Slave', 'Sleep', 'Sleeve', 'Slice', 'Slide',
  'Sling', 'Slip', 'Slope', 'Slot', 'Slow', 'Slump', 'Smell', 'Smile',
  'Smoke', 'Snack', 'Snail', 'Snake', 'Snap', 'Snare', 'Snatch', 'Sneak',
  'Sneeze', 'Sniff', 'Snob', 'Snore', 'Snow', 'Soap', 'Soccer', 'Society',
  'Sock', 'Soda', 'Sofa', 'Soft', 'Soil', 'Solar', 'Soldier', 'Solid',
  'Solution', 'Solvent', 'Son', 'Song', 'Sort', 'Sound', 'Soup', 'Source',
  'South', 'Space', 'Spade', 'Spare', 'Spark', 'Sparkle', 'Spatula', 'Speaker',
  'Spear', 'Special', 'Speech', 'Speed', 'Spell', 'Spend', 'Sphere', 'Spice',
  'Spider', 'Spike', 'Spill', 'Spin', 'Spine', 'Spiral', 'Spirit', 'Split',
  'Spoil', 'Sponge', 'Spoon', 'Sport', 'Spot', 'Spray', 'Spread', 'Spring',
  'Spy', 'Square', 'Squash', 'Squeeze', 'Squirrel', 'Stable', 'Stadium', 'Staff',
  'Stage', 'Stain', 'Stair', 'Stake', 'Stale', 'Stalk', 'Stamp', 'Stand',
  'Standard', 'Staple', 'Star', 'Stare', 'Start', 'State', 'Stay', 'Steak',
  'Steal', 'Steam', 'Steel', 'Steep', 'Steer', 'Stem', 'Step', 'Stereo',
  'Stick', 'Stiff', 'Stile', 'Still', 'Sting', 'Stir', 'Stock', 'Stomach',
  'Stone', 'Stool', 'Stop', 'Store', 'Storm', 'Story', 'Stove', 'Strain',
  'Strand', 'Strange', 'Stranger', 'Strap', 'Straw', 'Stream', 'Street', 'Strength',
  'Stress', 'Stretch', 'Strike', 'String', 'Strip', 'Stroke', 'Structure', 'Struggle',
  'Stub', 'Student', 'Studio', 'Study', 'Stuff', 'Stumble', 'Stump', 'Stupid',
  'Style', 'Subject', 'Substance', 'Subtle', 'Suburb', 'Subway', 'Success', 'Suck',
  'Sudden', 'Suffer', 'Sugar', 'Suit', 'Summer', 'Summit', 'Sun', 'Sunset',
  'Super', 'Supply', 'Support', 'Surface', 'Surge', 'Surplus', 'Surprise', 'Surround',
  'Survey', 'Survival', 'Suspect', 'Swamp', 'Swarm', 'Swap', 'Swear', 'Sweat',
  'Sweep', 'Sweet', 'Swell', 'Swift', 'Swim', 'Swing', 'Switch', 'Sword',
  'Symbol', 'Sympathy', 'Symphony', 'Symptom', 'Syndrome', 'System', 'Table', 'Tablet',
  'Tack', 'Tackle', 'Tact', 'Tag', 'Tail', 'Take', 'Tale', 'Talent',
  'Talk', 'Tank', 'Tap', 'Tape', 'Target', 'Tariff', 'Task', 'Taste',
  'Tattoo', 'Tax', 'Taxi', 'Tea', 'Teach', 'Team', 'Tear', 'Tease',
  'Temple', 'Tempo', 'Tenant', 'Tend', 'Tennis', 'Tension', 'Tent', 'Term',
  'Terminal', 'Test', 'Text', 'Thank', 'Theme', 'Theory', 'Therapy', 'Thick',
  'Thief', 'Thin', 'Thing', 'Think', 'Third', 'Thirst', 'Thread', 'Threat',
  'Thrill', 'Throat', 'Throne', 'Thunder', 'Ticket', 'Tide', 'Tiger', 'Tight',
  'Tile', 'Till', 'Timber', 'Time', 'Tin', 'Tip', 'Tire', 'Tissue',
  'Title', 'Toast', 'Tobacco', 'Today', 'Toe', 'Toga', 'Token', 'Tolerance',
  'Tomato', 'Tomb', 'Tone', 'Tongue', 'Tonight', 'Tool', 'Tooth', 'Top',
  'Topic', 'Tornado', 'Tortoise', 'Toss', 'Total', 'Touch', 'Tour', 'Towel',
  'Tower', 'Town', 'Toy', 'Track', 'Trade', 'Tradition', 'Traffic', 'Trail',
  'Train', 'Trait', 'Trance', 'Transfer', 'Transform', 'Transition', 'Trap', 'Trash',
  'Travel', 'Tray', 'Treasure', 'Treat', 'Treaty', 'Tree', 'Trend', 'Trial',
  'Triangle', 'Tribe', 'Trick', 'Trip', 'Troll', 'Troop', 'Trophy', 'Trouble',
  'Truck', 'Trunk', 'Trust', 'Truth', 'Try', 'Tube', 'Tulip', 'Tuna',
  'Tunnel', 'Turf', 'Turkey', 'Turn', 'Turtle', 'Tusk', 'Tutor', 'Tuxedo',
  'Twig', 'Twilight', 'Twin', 'Twist', 'Type', 'Typist', 'Umbrella', 'Uncle',
  'Under', 'Uniform', 'Union', 'Unique', 'Unit', 'Unity', 'Universe', 'Unknown',
  'Urban', 'Urge', 'Use', 'User', 'Usher', 'Vacuum', 'Valley', 'Value',
  'Valve', 'Van', 'Vapor', 'Variable', 'Variety', 'Vase', 'Vault', 'Vector',
  'Vegetable', 'Vehicle', 'Veil', 'Vein', 'Velocity', 'Velvet', 'Vendor', 'Venom',
  'Venture', 'Venue', 'Verb', 'Verdict', 'Verse', 'Version', 'Vertex', 'Vertical',
  'Vessel', 'Vest', 'Veteran', 'Veto', 'Vial', 'Vibe', 'Victim', 'Victory',
  'Video', 'View', 'Village', 'Vine', 'Vinegar', 'Violin', 'Viper', 'Virus',
  'Visible', 'Vision', 'Visit', 'Visitor', 'Visual', 'Vital', 'Vitamin', 'Vivid',
  'Voice', 'Void', 'Volcano', 'Volume', 'Vortex', 'Vote', 'Vow', 'Voyage',
  'Vulture', 'Wade', 'Waffle', 'Wage', 'Wagon', 'Waist', 'Wait', 'Wake',
  'Walk', 'Wall', 'Wallet', 'Walnut', 'Waltz', 'Wander', 'Want', 'War',
  'Ward', 'Warm', 'Warrant', 'Warrior', 'Wash', 'Wasp', 'Waste', 'Watch',
  'Water', 'Wave', 'Wax', 'Way', 'Wealth', 'Weapon', 'Wear', 'Weather',
  'Weave', 'Web', 'Wedding', 'Week', 'Weekend', 'Weight', 'Weird', 'Welcome',
  'Well', 'West', 'Wet', 'Whale', 'Wheat', 'Wheel', 'Where', 'Whip',
  'Whisper', 'White', 'Whole', 'Why', 'Width', 'Wife', 'Wild', 'Will',
  'Win', 'Wind', 'Window', 'Wine', 'Wing', 'Winner', 'Winter', 'Wire',
  'Wisdom', 'Wish', 'Witch', 'Witness', 'Wolf', 'Woman', 'Wonder', 'Wood',
  'Wool', 'Word', 'Work', 'World', 'Worm', 'Worry', 'Worth', 'Wrap',
  'Wreck', 'Wrist', 'Write', 'Wrong', 'Xenon', 'Xerox', 'Yacht', 'Yard',
  'Yarn', 'Year', 'Yellow', 'Yen', 'Yield', 'Yoga', 'Yogurt', 'Youth',
  'Zebra', 'Zen', 'Zero', 'Zest', 'Zigzag', 'Zone', 'Zoo', 'Zoom',
];

/**
 * Generate a random nickname from the adjective+noun lists.
 * Deterministic per session — stored in localStorage.
 */
export function generateNickname(): string {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  return `${adj} ${noun}`;
}

// ──────────────────────────────────────────────
// ICE server configuration
// ──────────────────────────────────────────────

/**
 * ARCH_REVIEW: ICE server list as a configurable parameter.
 *
 * Currently only uses Google's public STUN server. This is sufficient for
 * local dev and many NAT scenarios, but will fail on symmetric NATs.
 *
 * TODO: Add TURN server (Cloudflare Calls or third-party provider)
 * before real-user testing
 */
export const ICE_SERVERS: RTCIceServer[] = [
  { urls: 'stun:stun.l.google.com:19302' },
];

// ──────────────────────────────────────────────
// Constants
// ──────────────────────────────────────────────

/** Room expiry duration in milliseconds (30 minutes) */
export const ROOM_EXPIRY_MS = 30 * 60 * 1000;

/** Maximum chat message payload length */
export const MAX_MESSAGE_LENGTH = 4096;

/** WebSocket close codes */
export const WS_CLOSE_NORMAL = 1000;
export const WS_CLOSE_ROOM_EXPIRED = 4001;
export const WS_CLOSE_ROOM_FULL = 4002;
export const WS_CLOSE_ROOM_NOT_FOUND = 4003;