create extension if not exists pgcrypto;
create table public.networks(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,chain_id text);
create table public.sources(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,kind text not null,url text,access_status text not null default 'researching');
create table public.assets(id uuid primary key default gen_random_uuid(),name text unique not null,tld text not null,network_id uuid references public.networks(id),contract_address text,token_id text,metadata jsonb not null default '{}',created_at timestamptz default now(),updated_at timestamptz default now());
create table public.markets(id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.assets(id) on delete cascade,source_id uuid references public.sources(id),external_id text,market_type text not null,status text not null default 'active',price numeric,currency text not null default 'USD',bid_count int not null default 0,min_bid numeric,starts_at timestamptz,ends_at timestamptz,source_url text,metadata jsonb not null default '{}',observed_at timestamptz default now(),created_at timestamptz default now(),updated_at timestamptz default now());
create unique index markets_source_external on public.markets(source_id,external_id) where external_id is not null;
create index markets_feed on public.markets(status,price,ends_at);
create table public.market_events(id bigint generated always as identity primary key,market_id uuid not null references public.markets(id) on delete cascade,event_type text not null,price numeric,bid_count int,occurred_at timestamptz default now(),metadata jsonb not null default '{}');
alter table public.networks enable row level security;alter table public.sources enable row level security;alter table public.assets enable row level security;alter table public.markets enable row level security;alter table public.market_events enable row level security;
create policy p_networks on public.networks for select to anon,authenticated using(true);create policy p_sources on public.sources for select to anon,authenticated using(true);create policy p_assets on public.assets for select to anon,authenticated using(true);create policy p_markets on public.markets for select to anon,authenticated using(true);create policy p_events on public.market_events for select to anon,authenticated using(true);
insert into public.networks(slug,name,chain_id) values('ethereum','Ethereum','eip155:1'),('doma','Doma','doma:1');
insert into public.sources(slug,name,kind,url,access_status) values
('doma','Doma','indexer','https://doma.xyz','needs_credentials'),('godaddy','GoDaddy Auctions','market','https://auctions.godaddy.com','researching'),('namejet','NameJet','market','https://www.namejet.com','researching'),('dropcatch','DropCatch','market','https://www.dropcatch.com','researching'),('dynadot','Dynadot','market','https://www.dynadot.com','researching'),('dnw','Domain Name Wire','news','https://domainnamewire.com','ready'),('dnj','DNJournal','news','https://www.dnjournal.com','ready'),('di','Domain Incite','news','https://domainincite.com','ready'),('td','The Domains','news','https://www.thedomains.com','ready'),('div','DomainInvesting.com','news','https://domaininvesting.com','ready');